# Generated by Django 5.1.4 on 2024-12-07 23:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อของสิ่งอำนวยความสะดวก เช่น Wi-Fi, ทีวี, เครื่องปรับอากาศ', max_length=100, unique=True, verbose_name='ชื่อสิ่งอำนวยความสะดวก')),
                ('description', models.TextField(blank=True, help_text='คำอธิบายเพิ่มเติมเกี่ยวกับสิ่งอำนวยความสะดวก', null=True, verbose_name='รายละเอียด')),
            ],
            options={
                'verbose_name': 'สิ่งอำนวยความสะดวก',
                'verbose_name_plural': 'สิ่งอำนวยความสะดวก',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='หมายเลขห้องพัก เช่น 101, 102, 201 เป็นต้น', max_length=10, unique=True, verbose_name='หมายเลขห้อง')),
                ('type', models.CharField(help_text='ประเภทห้อง เช่น ห้องเดี่ยว, ห้องคู่, ห้องสวีท', max_length=100, verbose_name='ประเภทห้อง')),
                ('status', models.CharField(choices=[('AVAILABLE', 'ว่าง'), ('BOOKED', 'ถูกจอง'), ('MAINTENANCE', 'อยู่ระหว่างซ่อมแซม')], default='AVAILABLE', help_text='สถานะของห้องพัก เช่น ว่าง, ถูกจอง, อยู่ระหว่างซ่อมแซม', max_length=20, verbose_name='สถานะ')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='ราคาห้องพักต่อคืน', max_digits=10, verbose_name='ราคาต่อคืน')),
                ('size', models.FloatField(help_text='พื้นที่ของห้องพักในหน่วยตารางเมตร', verbose_name='พื้นที่ห้อง (ตารางเมตร)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='วันที่และเวลาที่ห้องพักถูกเพิ่มเข้าระบบ', verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='วันที่และเวลาที่ข้อมูลห้องพักถูกแก้ไขล่าสุด', verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'ห้องพัก',
                'verbose_name_plural': 'ห้องพัก',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAmenity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='ชื่อของสิ่งอำนวยความสะดวก เช่น Wi-Fi, ทีวี, เครื่องปรับอากาศ', max_length=100, verbose_name='ชื่อสิ่งอำนวยความสะดวก')),
                ('description', models.TextField(blank=True, help_text='คำอธิบายเพิ่มเติมเกี่ยวกับสิ่งอำนวยความสะดวก', null=True, verbose_name='รายละเอียด')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical สิ่งอำนวยความสะดวก',
                'verbose_name_plural': 'historical สิ่งอำนวยความสะดวก',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoom',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text='หมายเลขห้องพัก เช่น 101, 102, 201 เป็นต้น', max_length=10, verbose_name='หมายเลขห้อง')),
                ('type', models.CharField(help_text='ประเภทห้อง เช่น ห้องเดี่ยว, ห้องคู่, ห้องสวีท', max_length=100, verbose_name='ประเภทห้อง')),
                ('status', models.CharField(choices=[('AVAILABLE', 'ว่าง'), ('BOOKED', 'ถูกจอง'), ('MAINTENANCE', 'อยู่ระหว่างซ่อมแซม')], default='AVAILABLE', help_text='สถานะของห้องพัก เช่น ว่าง, ถูกจอง, อยู่ระหว่างซ่อมแซม', max_length=20, verbose_name='สถานะ')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='ราคาห้องพักต่อคืน', max_digits=10, verbose_name='ราคาต่อคืน')),
                ('size', models.FloatField(help_text='พื้นที่ของห้องพักในหน่วยตารางเมตร', verbose_name='พื้นที่ห้อง (ตารางเมตร)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='วันที่และเวลาที่ห้องพักถูกเพิ่มเข้าระบบ', verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='วันที่และเวลาที่ข้อมูลห้องพักถูกแก้ไขล่าสุด', verbose_name='แก้ไขเมื่อ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ห้องพัก',
                'verbose_name_plural': 'historical ห้องพัก',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoomAmenity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='จำนวนของสิ่งอำนวยความสะดวกในห้องพัก เช่น จำนวนเครื่องปรับอากาศ, จำนวนเตียง', verbose_name='จำนวน')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('amenity', models.ForeignKey(blank=True, db_constraint=False, help_text='สิ่งอำนวยความสะดวกที่เชื่อมต่อกับห้องพัก', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rooms.amenity', verbose_name='สิ่งอำนวยความสะดวก')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, db_constraint=False, help_text='ห้องพักที่มีสิ่งอำนวยความสะดวกนี้', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rooms.room', verbose_name='ห้องพัก')),
            ],
            options={
                'verbose_name': 'historical สิ่งอำนวยความสะดวกในห้องพัก',
                'verbose_name_plural': 'historical สิ่งอำนวยความสะดวกในห้องพัก',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='จำนวนของสิ่งอำนวยความสะดวกในห้องพัก เช่น จำนวนเครื่องปรับอากาศ, จำนวนเตียง', verbose_name='จำนวน')),
                ('amenity', models.ForeignKey(help_text='สิ่งอำนวยความสะดวกที่เชื่อมต่อกับห้องพัก', on_delete=django.db.models.deletion.CASCADE, to='rooms.amenity', verbose_name='สิ่งอำนวยความสะดวก')),
                ('room', models.ForeignKey(help_text='ห้องพักที่มีสิ่งอำนวยความสะดวกนี้', on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='ห้องพัก')),
            ],
            options={
                'verbose_name': 'สิ่งอำนวยความสะดวกในห้องพัก',
                'verbose_name_plural': 'สิ่งอำนวยความสะดวกในห้องพัก',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(help_text='สิ่งอำนวยความสะดวกที่มีในห้องพัก', through='rooms.RoomAmenity', to='rooms.amenity', verbose_name='สิ่งอำนวยความสะดวก'),
        ),
    ]
