# Generated by Django 5.1.4 on 2024-12-07 23:42

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStaff',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ชื่อเต็ม')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', 'กรุณากรอกหมายเลขโทรศัพท์ที่ถูกต้อง (9-15 ตัวเลข)')], verbose_name='เบอร์โทรศัพท์')),
                ('position', models.CharField(choices=[('Manager', 'ผู้จัดการ'), ('Staff', 'เจ้าหน้าที่'), ('Developer', 'นักพัฒนา'), ('Intern', 'นักศึกษาฝึกงาน')], default='Staff', max_length=50, verbose_name='ตำแหน่ง')),
                ('hire_date', models.DateField(verbose_name='วันที่เข้าทำงาน')),
                ('is_active', models.BooleanField(default=True, help_text='กำหนดว่าพนักงานยังคงทำงานอยู่หรือไม่', verbose_name='สถานะการใช้งาน')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='แก้ไขเมื่อ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical พนักงาน',
                'verbose_name_plural': 'historical พนักงาน',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ชื่อเต็ม')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', 'กรุณากรอกหมายเลขโทรศัพท์ที่ถูกต้อง (9-15 ตัวเลข)')], verbose_name='เบอร์โทรศัพท์')),
                ('position', models.CharField(choices=[('Manager', 'ผู้จัดการ'), ('Staff', 'เจ้าหน้าที่'), ('Developer', 'นักพัฒนา'), ('Intern', 'นักศึกษาฝึกงาน')], default='Staff', max_length=50, verbose_name='ตำแหน่ง')),
                ('hire_date', models.DateField(verbose_name='วันที่เข้าทำงาน')),
                ('is_active', models.BooleanField(default=True, help_text='กำหนดว่าพนักงานยังคงทำงานอยู่หรือไม่', verbose_name='สถานะการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['email'], name='staffs_staf_email_da3494_idx'), models.Index(fields=['phone'], name='staffs_staf_phone_7610d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_email'), models.UniqueConstraint(fields=('phone',), name='unique_phone')],
            },
        ),
    ]
